name: Read index.html and Print Content

on:
  push:
    branches:
      - master

jobs:
  read-file:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Read and print the content of index.html
      - name: Display file content
        run: |
          echo "Content of index.html:"
          cat index.html
