name: Read index.html and Print Content

on:
  push:
    branches:
      - master   # or 'main' if your repo uses main

jobs:
  read-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display file content
        run: |
          echo "Content of index.html:"
          cat index.html
